services:
  - type: web
    name: bot-whatsapp
    runtime: node
    buildCommand: |
      apt-get update && apt-get install -y \
        chromium \
        libatk-bridge2.0-0 \
        libdrm2 \
        libxkbcommon0 \
        libxcomposite1 \
        libxdamage1 \
        libxrandr2 \
        libgbm1 \
        libasound2 \
        && npm install
    startCommand: node index.js
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: PUPPETEER_EXECUTABLE_PATH
        value: /usr/bin/chromium
      - key: RENDER
        value: true
